<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>DupDetector.Reporting.Tests</RootNamespace>
        <AssemblyName>DupDetector.Reporting.Tests</AssemblyName>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <GenerateProgramFile>false</GenerateProgramFile>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CA1707;CA2201;CA1861;CA1515</NoWarn>
        <NoWarn>$(NoWarn);EnableGenerateDocumentationFile</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\TestEntryPoint.cs" Link="TestEntryPoint.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\DupDetector.Reporting\DupDetector.Reporting.csproj" />
        <ProjectReference Include="..\DupDetector.TestKit\DupDetector.TestKit.csproj" />
    </ItemGroup>

</Project>