namespace DupDetector.Sources;

/// <summary>
///     Recognises machine-generated files.
/// </summary>
public static class GeneratedFileDetector
{
    /// <summary>
    ///     How far into a file a generated-code marker is still considered a header marker.
    /// </summary>
    public const int HeaderLineCount = 30;
    private static readonly string[] HeaderMarkers;
    private static readonly string[] NameMarkers;

    static GeneratedFileDetector()
    {
        HeaderMarkers = ["<auto-generated", "[GeneratedCode", "[global::System.CodeDom.Compiler.GeneratedCode"];

        NameMarkers = [".designer.", ".g.", ".generated."];
    }

    /// <summary>
    ///     
    /// </summary>
    /// <returns></returns>
    /// <param name="fileName"></param>
    public static bool HasGeneratedName(string fileName)
    {
        var name = Path.GetFileName(fileName);
        return Array.Exists(NameMarkers, marker => name.Contains(marker, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    ///     
    /// </summary>
    /// <returns></returns>
    /// <param name="content"></param>
    public static bool HasHeaderMarker(string content)
    {
        foreach (var line in EnumerateHeaderLines(content))
        {
            if (Array.Exists(HeaderMarkers, marker => line.Contains(marker, StringComparison.OrdinalIgnoreCase)))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    ///     
    /// </summary>
    /// <returns></returns>
    /// <param name="fileName"></param>
    /// <param name="content"></param>
    public static bool IsGenerated(string fileName, string content)
    {

        return HasGeneratedName(fileName) || HasHeaderMarker(content);
    }

    private static IEnumerable<string> EnumerateHeaderLines(string content)
    {
        var start = 0;
        for (var line = 0; line < HeaderLineCount && start < content.Length; line++)
        {
            var end = content.IndexOf('\n', start);
            if (end < 0)
            {
                yield return content[start..];
                yield break;
            }

            yield return content[start..end];
            start = end + 1;
        }
    }
}
