namespace DupDetector.Sources;

/// <summary>
/// Recognises machine-generated files.
/// </summary>
/// <remarks>
/// Content markers are only honoured in the file header, where the convention places them. Scanning
/// the whole body meant any file that merely mentioned a marker excluded itself.
/// </remarks>
public static class GeneratedFileDetector
{
    /// <summary>How far into a file a generated-code marker is still considered a header marker.</summary>
    public const int HeaderLineCount = 30;

    private static readonly string[] NameMarkers = [".designer.", ".g.", ".generated."];
    private static readonly string[] HeaderMarkers = ["<auto-generated", "[GeneratedCode", "[global::System.CodeDom.Compiler.GeneratedCode"];

    public static bool IsGenerated(string fileName, string content)
    {
        ArgumentNullException.ThrowIfNull(fileName);
        ArgumentNullException.ThrowIfNull(content);

        return HasGeneratedName(fileName) || HasHeaderMarker(content);
    }

    internal static bool HasGeneratedName(string fileName)
    {
        var name = Path.GetFileName(fileName);
        return Array.Exists(NameMarkers, marker => name.Contains(marker, StringComparison.OrdinalIgnoreCase));
    }

    internal static bool HasHeaderMarker(string content)
    {
        foreach (var line in EnumerateHeaderLines(content))
        {
            if (Array.Exists(HeaderMarkers, marker => line.Contains(marker, StringComparison.OrdinalIgnoreCase)))
            {
                return true;
            }
        }

        return false;
    }

    private static IEnumerable<string> EnumerateHeaderLines(string content)
    {
        var start = 0;
        for (var line = 0; line < HeaderLineCount && start < content.Length; line++)
        {
            var end = content.IndexOf('\n', start);
            if (end < 0)
            {
                yield return content[start..];
                yield break;
            }

            yield return content[start..end];
            start = end + 1;
        }
    }
}
