using Microsoft.Build.Locator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.MSBuild;

namespace DupDetector;

/// <summary>
/// Loads C# source documents from .sln, .csproj, or directory paths.
/// Falls back to text-based parsing when MSBuildWorkspace is unavailable.
/// </summary>
public class ProjectLoader
{
    private readonly DetectionOptions _options;

    public ProjectLoader(DetectionOptions options)
    {
        _options = options;
    }

    public async Task<List<(string FilePath, SyntaxTree SyntaxTree, string SourceText)>> LoadAsync(string path)
    {
        if (File.Exists(path))
        {
            var ext = Path.GetExtension(path).ToLowerInvariant();
            if (ext == ".sln" || ext == ".csproj")
            {
                try
                {
                    return await LoadFromWorkspaceAsync(path);
                }
                catch (Exception ex)
                {
                    // MSBuildWorkspace may fail in CI environments without a full MSBuild installation.
                    // Fall back to text-based parsing of the referenced files.
                    Console.Error.WriteLine($"[warn] MSBuildWorkspace failed ({ex.Message}), falling back to directory scan.");
                    var dir = Path.GetDirectoryName(path) ?? ".";
                    return LoadFromDirectory(dir);
                }
            }

            // Single .cs file
            if (ext == ".cs")
            {
                return LoadFiles(new[] { path });
            }
        }

        if (Directory.Exists(path))
        {
            return LoadFromDirectory(path);
        }

        throw new ArgumentException($"Path does not exist: {path}");
    }

    private async Task<List<(string, SyntaxTree, string)>> LoadFromWorkspaceAsync(string path)
    {
        using var workspace = MSBuildWorkspace.Create();
        workspace.WorkspaceFailed += (_, e) =>
            Console.Error.WriteLine($"[workspace] {e.Diagnostic.Kind}: {e.Diagnostic.Message}");

        var ext = Path.GetExtension(path).ToLowerInvariant();

        IEnumerable<Document> documents;
        if (ext == ".sln")
        {
            var solution = await workspace.OpenSolutionAsync(path);
            documents = solution.Projects.SelectMany(p => p.Documents);
        }
        else
        {
            var project = await workspace.OpenProjectAsync(path);
            documents = project.Documents;
        }

        var results = new List<(string, SyntaxTree, string)>();
        foreach (var doc in documents)
        {
            if (doc.FilePath == null) continue;
            if (ShouldExclude(doc.FilePath)) continue;

            var sourceText = await doc.GetTextAsync();
            var syntaxTree = await doc.GetSyntaxTreeAsync();
            if (syntaxTree == null) continue;

            var text = sourceText.ToString();
            if (!_options.IncludeGenerated && IsGeneratedFile(doc.FilePath, text)) continue;

            results.Add((doc.FilePath, syntaxTree, text));
        }
        return results;
    }

    private List<(string, SyntaxTree, string)> LoadFromDirectory(string dir)
    {
        var files = Directory.EnumerateFiles(dir, "*.cs", SearchOption.AllDirectories)
            .Where(f => !ShouldExclude(f))
            .ToList();
        return LoadFiles(files);
    }

    private List<(string, SyntaxTree, string)> LoadFiles(IEnumerable<string> files)
    {
        var results = new List<(string, SyntaxTree, string)>();
        foreach (var file in files)
        {
            try
            {
                var text = File.ReadAllText(file);
                if (!_options.IncludeGenerated && IsGeneratedFile(file, text)) continue;

                var syntaxTree = CSharpSyntaxTree.ParseText(text, path: file);
                results.Add((file, syntaxTree, text));
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"[warn] Failed to read {file}: {ex.Message}");
            }
        }
        return results;
    }

    private bool ShouldExclude(string filePath)
    {
        foreach (var pattern in _options.Exclude)
        {
            if (GlobMatch(pattern, filePath)) return true;
        }
        return false;
    }

    private static bool IsGeneratedFile(string filePath, string content)
    {
        var fileName = Path.GetFileName(filePath);
        if (fileName.Contains(".Designer.", StringComparison.OrdinalIgnoreCase)) return true;
        if (fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)) return true;
        if (fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)) return true;
        if (content.Contains("<auto-generated>", StringComparison.OrdinalIgnoreCase)) return true;
        if (content.Contains("[GeneratedCode", StringComparison.OrdinalIgnoreCase)) return true;
        return false;
    }

    /// <summary>Simple glob matching supporting * and ? wildcards.</summary>
    private static bool GlobMatch(string pattern, string filePath)
    {
        // Normalize separators
        filePath = filePath.Replace('\\', '/');
        pattern = pattern.Replace('\\', '/');
        return GlobMatchCore(pattern, filePath);
    }

    private static bool GlobMatchCore(string pattern, string input)
    {
        int p = 0, i = 0;
        int starP = -1, starI = 0;

        while (i < input.Length)
        {
            if (p < pattern.Length && (pattern[p] == '?' || pattern[p] == input[i]))
            {
                p++; i++;
            }
            else if (p < pattern.Length && pattern[p] == '*')
            {
                starP = p++;
                starI = i;
            }
            else if (starP != -1)
            {
                p = starP + 1;
                i = ++starI;
            }
            else return false;
        }

        while (p < pattern.Length && pattern[p] == '*') p++;
        return p == pattern.Length;
    }
}
