using System.Text;
using DupDetector.Core.Model;
using Xunit;

namespace DupDetector.Sources.Tests;

/// <summary>
/// A disposable temporary directory tree.
/// </summary>
public sealed class TempTree : IDisposable
{
    public TempTree()
    {
        Root = Path.Combine(Path.GetTempPath(), "dupdetector-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(Root);
    }

    public string Root { get; }

    public string Write(string relativePath, string content)
    {
        var full = Path.Combine(Root, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllText(full, content, new UTF8Encoding(false));
        return full;
    }

    public string WriteBytes(string relativePath, byte[] content)
    {
        var full = Path.Combine(Root, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllBytes(full, content);
        return full;
    }

    public void Dispose()
    {
        try
        {
            Directory.Delete(Root, recursive: true);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            // A leftover temp directory is not worth failing a test over.
        }
    }
}

public class FileSystemSourceProviderTests
{
    private static readonly DetectionSettings Settings = new() { MinLines = 1 };

    [Fact]
    public void Load_RejectsNullArguments()
    {
        var provider = new FileSystemSourceProvider();
        Assert.Throws<ArgumentNullException>(() => provider.Load(null!, Settings));
        Assert.Throws<ArgumentNullException>(() => provider.Load(".", null!));
    }

    [Fact]
    public void Load_ReportsAMissingPathAsAnError()
    {
        var result = new FileSystemSourceProvider().Load(
            Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString()),
            Settings);

        Assert.Empty(result.Units);
        var diagnostic = Assert.Single(result.Diagnostics);
        Assert.Equal(SourceDiagnosticSeverity.Error, diagnostic.Severity);
    }

    [Fact]
    public void Load_ReadsASingleFile()
    {
        using var tree = new TempTree();
        var file = tree.Write("App/Service.cs", "class Service { }");
        tree.Write("App/App.csproj", "<Project />");

        var result = new FileSystemSourceProvider().Load(file, Settings);

        var unit = Assert.Single(result.Units);
        Assert.Equal(file, unit.Path);
        Assert.Equal(ProjectIdentity.Named("App"), unit.Project);
        Assert.Equal(DiscoveryMode.FileSystem, result.Stats.Mode);
        Assert.Equal(1, result.Stats.Discovered);
    }

    [Fact]
    public void Load_WalksADirectoryAndResolvesProjects()
    {
        using var tree = new TempTree();
        tree.Write("App/App.csproj", "<Project />");
        tree.Write("App/Service.cs", "class Service { }");
        tree.Write("Lib/Lib.csproj", "<Project />");
        tree.Write("Lib/Helper.cs", "class Helper { }");

        var result = new FileSystemSourceProvider().Load(tree.Root, Settings);

        Assert.Equal(2, result.Units.Count);
        Assert.Contains(result.Units, unit => unit.Project == ProjectIdentity.Named("App"));
        Assert.Contains(result.Units, unit => unit.Project == ProjectIdentity.Named("Lib"));
        Assert.Empty(result.Diagnostics);
    }

    [Fact]
    public void Load_SkipsBuildArtifacts()
    {
        using var tree = new TempTree();
        tree.Write("Service.cs", "class Service { }");
        tree.Write("obj/Debug/Generated.cs", "class Generated { }");
        tree.Write("bin/Release/Other.cs", "class Other { }");
        // A directory whose name merely starts with bin is not an artifact directory.
        tree.Write("bindings/Real.cs", "class Real { }");

        var result = new FileSystemSourceProvider().Load(tree.Root, Settings);

        Assert.Equal(2, result.Units.Count);
        Assert.Equal(2, result.Stats.Excluded);
        Assert.Contains(result.Units, unit => unit.Path.EndsWith("Real.cs", StringComparison.Ordinal));
    }

    [Fact]
    public void Load_AppliesExcludeGlobs()
    {
        using var tree = new TempTree();
        tree.Write("src/Service.cs", "class Service { }");
        tree.Write("gen/Model.cs", "class Model { }");

        var result = new FileSystemSourceProvider().Load(
            tree.Root,
            Settings with { ExcludeFileGlobs = ["gen/**"] });

        var unit = Assert.Single(result.Units);
        Assert.EndsWith("Service.cs", unit.Path, StringComparison.Ordinal);
    }

    [Fact]
    public void Load_SkipsGeneratedFiles()
    {
        using var tree = new TempTree();
        tree.Write("Service.cs", "class Service { }");
        tree.Write("Model.g.cs", "class Model { }");
        tree.Write("Header.cs", "// <auto-generated />\nclass Header { }");

        var result = new FileSystemSourceProvider().Load(tree.Root, Settings);

        Assert.Single(result.Units);
        Assert.Equal(2, result.Stats.Excluded);
    }

    [Fact]
    public void Load_ClassifiesTestFilesAndCanExcludeThemEntirely()
    {
        using var tree = new TempTree();
        tree.Write("src/Service.cs", "class Service { }");
        tree.Write("tests/ServiceTests.cs", "class ServiceTests { }");
        // Word-boundary classification keeps this production file in.
        tree.Write("src/Latest.cs", "class Latest { }");

        var included = new FileSystemSourceProvider().Load(tree.Root, Settings);
        Assert.Equal(3, included.Units.Count);
        Assert.Single(included.Units, unit => unit.IsTestFile);

        var excluded = new FileSystemSourceProvider().Load(tree.Root, Settings with { ExcludeTestFiles = true });
        Assert.Equal(2, excluded.Units.Count);
        Assert.DoesNotContain(excluded.Units, unit => unit.IsTestFile);
    }

    [Fact]
    public void Load_ReportsParseFailuresWithoutDiscardingTheFile()
    {
        using var tree = new TempTree();
        tree.Write("Broken.cs", "class C { void M( }");

        var result = new FileSystemSourceProvider().Load(tree.Root, Settings);

        Assert.Single(result.Units);
        var diagnostic = Assert.Single(result.Diagnostics);
        Assert.Equal(SourceDiagnosticSeverity.Warning, diagnostic.Severity);
    }

    [Fact]
    public void Load_ReadsUtf16FilesWithoutCorruption()
    {
        using var tree = new TempTree();
        const string Text = "class Widget { public int Value { get; set; } }";
        tree.WriteBytes("Widget.cs", Encoding.Unicode.GetBytes(Text));

        var unit = Assert.Single(new FileSystemSourceProvider().Load(tree.Root, Settings).Units);

        Assert.Equal(Text, unit.Text);
        Assert.DoesNotContain('\0', unit.Text);
    }

    [Fact]
    public void Load_HonoursCancellation()
    {
        using var tree = new TempTree();
        tree.Write("Service.cs", "class Service { }");
        using var cancellation = new CancellationTokenSource();
        cancellation.Cancel();

        Assert.Throws<OperationCanceledException>(() =>
            new FileSystemSourceProvider().Load(tree.Root, Settings, cancellation.Token));
    }

    [Fact]
    public void Load_SurvivesAnInaccessibleSubdirectory()
    {
        using var tree = new TempTree();
        tree.Write("Top.cs", "class Top { }");
        tree.Write("allowed/Allowed.cs", "class Allowed { }");

        var denied = Path.Combine(tree.Root, "denied");
        Directory.CreateDirectory(denied);
        File.WriteAllText(Path.Combine(denied, "Hidden.cs"), "class Hidden { }");

        var result = new FileSystemSourceProvider().Load(tree.Root, Settings);

        // The scan completes and the readable files are analysed regardless of the denied folder.
        Assert.Contains(result.Units, unit => unit.Path.EndsWith("Top.cs", StringComparison.Ordinal));
        Assert.Contains(result.Units, unit => unit.Path.EndsWith("Allowed.cs", StringComparison.Ordinal));
    }

    [Fact]
    public void Load_ReportsAnUnreadableFileWithoutAbortingTheScan()
    {
        using var tree = new TempTree();
        tree.Write("Readable.cs", "class Readable { }");
        var locked = tree.Write("Locked.cs", "class Locked { }");

        using (new FileStream(locked, FileMode.Open, FileAccess.Read, FileShare.None))
        {
            var result = new FileSystemSourceProvider().Load(tree.Root, Settings);

            Assert.Single(result.Units);
            Assert.EndsWith("Readable.cs", result.Units[0].Path, StringComparison.Ordinal);

            var diagnostic = Assert.Single(result.Diagnostics);
            Assert.Equal(SourceDiagnosticSeverity.Warning, diagnostic.Severity);
            Assert.Equal(locked, diagnostic.Path);
            Assert.Equal(1, result.Stats.Excluded);
        }
    }

    [Fact]
    public void Relative_ProducesForwardSlashPathsBelowTheRoot()
    {
        var root = Path.GetFullPath(Path.Combine("C:", "repo"));
        Assert.Equal("src/App/Service.cs", FileSystemSourceProvider.Relative(root, Path.Combine(root, "src", "App", "Service.cs")));
    }

    [Theory]
    [InlineData("obj/Debug/A.cs", true)]
    [InlineData("bin/Release/A.cs", true)]
    [InlineData("src/OBJ/A.cs", true)]
    [InlineData("bindings/A.cs", false)]
    [InlineData("src/A.cs", false)]
    public void IsArtifact_MatchesWholeSegmentsOnly(string relativePath, bool expected) =>
        Assert.Equal(expected, FileSystemSourceProvider.IsArtifact(relativePath));
}
