
using Xunit;

namespace DupDetector.Sources.Tests;

/// <summary>
///     
/// </summary>
public class GeneratedFileDetectorTests
{

    /// <summary>
    ///     
    /// </summary>
    [Fact]
    public void IsGenerated_HandlesFileWithoutNewlines()
    {
        Assert.False(GeneratedFileDetector.HasHeaderMarker("class C { }"));
    }

    /// <summary>
    ///     
    /// </summary>
    [Fact]
    public void IsGenerated_HonoursHeaderMarkers()
    {
        Assert.True(GeneratedFileDetector.IsGenerated("C.cs", "// <auto-generated />\nclass C { }"));
    }

    /// <summary>
    ///     
    /// </summary>
    [Fact]
    public void IsGenerated_IgnoresMarkersOutsideTheHeader()
    {
        var lines = new List<string>(61);
        for (var index = 0; index < 60; index++)
        {
            lines.Add("// filler");
        }

        lines.Add("if (x.Contains(\"[GeneratedCode\")) { }");
        var content = string.Join('\n', lines);

        Assert.False(GeneratedFileDetector.IsGenerated("Loader.cs", content));
    }

    /// <summary>
    ///     
    /// </summary>
    [Fact]
    public void IsGenerated_ReadsMarkerOnTheLastLineOfShortFile()
    {
        Assert.True(GeneratedFileDetector.HasHeaderMarker("class C { }\n// <auto-generated"));
    }

    /// <summary>
    ///     
    /// </summary>
    /// <param name="fileName"></param>
    /// <param name="expected"></param>
    [Theory]
    [InlineData("Form.Designer.cs", true)]
    [InlineData("Model.g.cs", true)]
    [InlineData("Model.generated.cs", true)]
    [InlineData("OrderService.cs", false)]
    public void IsGenerated_RecognisesGeneratedNames(string fileName, bool expected)
    {
        Assert.Equal(expected, GeneratedFileDetector.HasGeneratedName(fileName));
    }
}
